### ISSUE TITLE
Situación actual

### ISSUE THREAD

**Issue by inrumi** [siulpolb/alliance_starter_pack#11]
Hey!, hola, gracias por crear este repo, quería saber en qué situación están ahora? estoy a punto de aceptar la oferta, pero me gustaría saber a qué me meto..., ya que en glassdoor hay unos reviews bastante feos.

**Comment by siulpolb** [comment]
Hola,

Para ser honesto desconozco la situación actual de la empresa debido a que me separe de ella hace como un año, pero no creo que haya cambiado mucho respecto a lo que se comenta en este repo.

Igual puedes pedir acceso a este grupo https://www.facebook.com/groups/MexicanSoftwareDevsUSA y pedir información ahí

Espero que esta información te sea útil

**Comment by inrumi** [comment]
Otra duda, en cuestion al tiempo que estuviste ahi valio la pena aceptar la oferta?

**Comment by siulpolb** [comment]
En mi experiencia personal si, me abrió muchas oportunidades que en México no es tan fácil encontrar

**Comment by inrumi** [comment]
Muchas gracias por la información
